#!/usr/bin/env python3
"""Generate synthetic canonical radar RCS mesh assets for Sinclair.

The assets are intentionally simple, project-generated geometry. They are not
measured RCS assets and not high-fidelity CAD. Their purpose is to provide a
clean first asset-library layer for RadarSim `sim_rcs` experiments.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSET_ROOT = ROOT / "public" / "assets" / "radar-rcs-library"


Vec3 = tuple[float, float, float]
Face = tuple[int, ...]


@dataclass
class Mesh:
    vertices: list[Vec3]
    faces: list[Face]

    def extend(self, other: "Mesh") -> None:
        offset = len(self.vertices)
        self.vertices.extend(other.vertices)
        self.faces.extend(tuple(index + offset for index in face) for face in other.faces)


def cuboid(center: Vec3, size: Vec3) -> Mesh:
    cx, cy, cz = center
    sx, sy, sz = (value / 2 for value in size)
    vertices = [
        (cx - sx, cy - sy, cz - sz),
        (cx + sx, cy - sy, cz - sz),
        (cx + sx, cy + sy, cz - sz),
        (cx - sx, cy + sy, cz - sz),
        (cx - sx, cy - sy, cz + sz),
        (cx + sx, cy - sy, cz + sz),
        (cx + sx, cy + sy, cz + sz),
        (cx - sx, cy + sy, cz + sz),
    ]
    faces = [
        (1, 2, 3, 4),
        (5, 8, 7, 6),
        (1, 5, 6, 2),
        (2, 6, 7, 3),
        (3, 7, 8, 4),
        (4, 8, 5, 1),
    ]
    return Mesh(vertices, faces)


def cylinder(center: Vec3, radius: float, height: float, segments: int = 16, axis: str = "z") -> Mesh:
    cx, cy, cz = center
    vertices: list[Vec3] = []
    for z_offset in (-height / 2, height / 2):
        for idx in range(segments):
            angle = 2 * math.pi * idx / segments
            x = radius * math.cos(angle)
            y = radius * math.sin(angle)
            if axis == "z":
                vertices.append((cx + x, cy + y, cz + z_offset))
            elif axis == "x":
                vertices.append((cx + z_offset, cy + x, cz + y))
            elif axis == "y":
                vertices.append((cx + x, cy + z_offset, cz + y))
            else:
                raise ValueError(f"Unsupported cylinder axis: {axis}")

    faces: list[Face] = []
    bottom = tuple(range(segments, 0, -1))
    top = tuple(range(segments + 1, 2 * segments + 1))
    faces.append(bottom)
    faces.append(top)
    for idx in range(segments):
        a = idx + 1
        b = ((idx + 1) % segments) + 1
        c = b + segments
        d = a + segments
        faces.append((a, b, c, d))
    return Mesh(vertices, faces)


def write_obj(path: Path, mesh: Mesh, name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Sinclair synthetic radar RCS asset: {name}",
        "# Units: meters",
        "# Generated by scripts/generate_radar_rcs_assets.py",
        f"o {name}",
    ]
    lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in mesh.vertices)
    lines.extend("f " + " ".join(str(index) for index in face) for face in mesh.faces)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def make_sedan() -> Mesh:
    mesh = Mesh([], [])
    mesh.extend(cuboid((0.0, 0.0, 0.55), (4.6, 1.85, 0.75)))
    mesh.extend(cuboid((-0.35, 0.0, 1.12), (2.35, 1.55, 0.72)))
    mesh.extend(cuboid((1.95, 0.0, 0.52), (0.45, 1.78, 0.42)))
    mesh.extend(cuboid((-2.05, 0.0, 0.48), (0.38, 1.78, 0.38)))
    for x in (-1.55, 1.55):
        for y in (-0.98, 0.98):
            mesh.extend(cylinder((x, y, 0.32), 0.34, 0.18, segments=18, axis="y"))
    return mesh


def make_pedestrian() -> Mesh:
    mesh = Mesh([], [])
    mesh.extend(cylinder((0.0, 0.0, 0.95), 0.22, 1.15, segments=18, axis="z"))
    mesh.extend(cylinder((0.0, 0.0, 1.62), 0.16, 0.24, segments=18, axis="z"))
    mesh.extend(cylinder((-0.11, 0.0, 0.32), 0.07, 0.64, segments=12, axis="z"))
    mesh.extend(cylinder((0.11, 0.0, 0.32), 0.07, 0.64, segments=12, axis="z"))
    mesh.extend(cylinder((-0.32, 0.0, 0.93), 0.055, 0.82, segments=12, axis="z"))
    mesh.extend(cylinder((0.32, 0.0, 0.93), 0.055, 0.82, segments=12, axis="z"))
    return mesh


def make_cyclist() -> Mesh:
    mesh = Mesh([], [])
    # Rider.
    mesh.extend(cylinder((0.0, 0.0, 1.16), 0.19, 0.92, segments=16, axis="z"))
    mesh.extend(cylinder((0.0, 0.0, 1.78), 0.14, 0.22, segments=16, axis="z"))
    # Bicycle wheels and frame approximations.
    for x in (-0.72, 0.72):
        mesh.extend(cylinder((x, 0.0, 0.42), 0.36, 0.055, segments=24, axis="y"))
    mesh.extend(cuboid((0.0, 0.0, 0.77), (1.55, 0.055, 0.08)))
    mesh.extend(cuboid((-0.32, 0.0, 0.88), (0.08, 0.055, 0.68)))
    mesh.extend(cuboid((0.5, 0.0, 0.92), (0.08, 0.055, 0.58)))
    mesh.extend(cuboid((0.73, 0.0, 1.06), (0.42, 0.055, 0.08)))
    return mesh


def make_guardrail() -> Mesh:
    mesh = Mesh([], [])
    mesh.extend(cuboid((0.0, 0.0, 0.78), (12.0, 0.18, 0.38)))
    for x in (-5.2, -2.6, 0.0, 2.6, 5.2):
        mesh.extend(cuboid((x, 0.0, 0.36), (0.16, 0.16, 0.72)))
    return mesh


def make_plate() -> Mesh:
    return cuboid((0.0, 0.0, 0.0), (1.0, 0.025, 1.0))


ASSETS = [
    {
        "id": "canonical_sedan_v1",
        "class": "vehicle",
        "category": "vehicles",
        "mesh": make_sedan,
        "dimensionsM": {"length": 4.6, "width": 1.85, "height": 1.55},
        "materialPreset": "mixed_vehicle_pec_like",
        "permittivity": None,
        "nominalRcsDbsm": 12.0,
        "defaultAspectSweepDeg": [-90, -60, -30, 0, 30, 60, 90],
        "notes": "Simplified sedan body, cabin, bumpers, and wheel cylinders.",
    },
    {
        "id": "canonical_pedestrian_v1",
        "class": "pedestrian",
        "category": "pedestrians",
        "mesh": make_pedestrian,
        "dimensionsM": {"length": 0.72, "width": 0.55, "height": 1.74},
        "materialPreset": "human_body_dielectric_approx",
        "permittivity": {"real": 38.0, "imag": -14.0},
        "nominalRcsDbsm": -3.0,
        "defaultAspectSweepDeg": [-90, -60, -30, 0, 30, 60, 90],
        "notes": "Capsule-like body approximation. Not posture or micro-Doppler resolved.",
    },
    {
        "id": "canonical_cyclist_v1",
        "class": "cyclist",
        "category": "cyclists",
        "mesh": make_cyclist,
        "dimensionsM": {"length": 1.75, "width": 0.62, "height": 1.9},
        "materialPreset": "mixed_bicycle_rider_approx",
        "permittivity": None,
        "nominalRcsDbsm": 2.0,
        "defaultAspectSweepDeg": [-90, -60, -30, 0, 30, 60, 90],
        "notes": "Rider plus coarse bicycle frame/wheel approximation.",
    },
    {
        "id": "canonical_guardrail_v1",
        "class": "guardrail",
        "category": "infrastructure",
        "mesh": make_guardrail,
        "dimensionsM": {"length": 12.0, "width": 0.22, "height": 0.98},
        "materialPreset": "metal_guardrail_pec_like",
        "permittivity": None,
        "nominalRcsDbsm": -5.0,
        "defaultAspectSweepDeg": [-80, -60, -40, -20, 0, 20, 40, 60, 80],
        "notes": "Long rail segment with posts. Useful for ghost/multipath scenario setup.",
    },
    {
        "id": "calibration_plate_1m_v1",
        "class": "calibration_reflector",
        "category": "reflectors",
        "mesh": make_plate,
        "dimensionsM": {"length": 1.0, "width": 0.025, "height": 1.0},
        "materialPreset": "flat_plate_pec_like",
        "permittivity": None,
        "nominalRcsDbsm": 27.0,
        "defaultAspectSweepDeg": [-80, -60, -40, -20, 0, 20, 40, 60, 80],
        "notes": "Simple plate for RadarSim RCS smoke tests and angular sweep sanity checks.",
    },
]


def build_asset_metadata(entry: dict) -> dict:
    mesh_rel = f"{entry['category']}/{entry['id']}.obj"
    meta_rel = f"{entry['category']}/{entry['id']}.json"
    radarsim_target = {
        "model": mesh_rel,
        "location": [0.0, 0.0, 0.0],
        "rotation": [0.0, 0.0, 0.0],
        "scale": 1.0,
    }
    if entry["permittivity"] is not None:
        radarsim_target["permittivity"] = entry["permittivity"]

    return {
        "id": entry["id"],
        "class": entry["class"],
        "source": "sinclair_synthetic_canonical_mesh",
        "license": "project-generated-no-external-asset-dependency",
        "fidelity": "canonical_mesh_estimate",
        "mesh": mesh_rel,
        "metadata": meta_rel,
        "units": "meters",
        "dimensionsM": entry["dimensionsM"],
        "materialPreset": entry["materialPreset"],
        "nominalRcsDbsm": entry["nominalRcsDbsm"],
        "permittivity": entry["permittivity"],
        "defaultAspectSweepDeg": entry["defaultAspectSweepDeg"],
        "rcsUsagePolicy": {
            "rawSimRcsAbsoluteDbsm": "not_validated_for_physical_truth",
            "recommended": "Use RadarSim sim_rcs for aspect-angle response shape, then normalize to nominalRcsDbsm until measured or validated CAD/material data is available.",
            "calibrationDbsmAtBroadside": entry["nominalRcsDbsm"],
            "futureUpgrade": "Replace nominalRcsDbsm with measured RCS tables or validated ray-traced RCS distributions.",
        },
        "radarsim": {
            "engine": "radarsimpy_whitebox.sim_rcs",
            "targetTemplate": radarsim_target,
            "recommendedFrequencyHz": 77e9,
        },
        "limitations": [
            "Not measured RCS data.",
            "Not high-fidelity automotive CAD.",
            "Raw sim_rcs absolute magnitude is not validated as physical truth for these canonical meshes.",
            "No radome, ground multipath, pose articulation, or material-layer model.",
            "Use for fast design estimates before measured or ray-traced assets are connected.",
        ],
        "notes": entry["notes"],
    }


def main() -> None:
    ASSET_ROOT.mkdir(parents=True, exist_ok=True)
    manifest_assets = []

    for entry in ASSETS:
        metadata = build_asset_metadata(entry)
        mesh = entry["mesh"]()
        mesh_path = ASSET_ROOT / metadata["mesh"]
        meta_path = ASSET_ROOT / metadata["metadata"]
        write_obj(mesh_path, mesh, entry["id"])
        write_json(meta_path, metadata)
        manifest_assets.append({key: metadata[key] for key in ("id", "class", "fidelity", "mesh", "metadata", "dimensionsM", "materialPreset")})

    manifest = {
        "schema": "sinclair.radarRcsAssetLibrary.v1",
        "generatedBy": "scripts/generate_radar_rcs_assets.py",
        "root": "/assets/radar-rcs-library",
        "rcsEngine": "RadarSim radarsimpy_whitebox.sim_rcs",
        "defaultFrequencyHz": 77e9,
        "assetCount": len(manifest_assets),
        "assets": manifest_assets,
        "sourceBoundary": {
            "current": "Synthetic canonical mesh assets generated inside this project.",
            "notIncluded": "Measured vehicle/pedestrian/cyclist RCS data, production CAD, full EM ray tracing.",
            "recommendedNextStep": "Add measured RCS tables or validated CAD/material assets while keeping this manifest schema.",
        },
        "rcsUsagePolicy": {
            "recommended": "Do not use raw sim_rcs absolute dBsm from these simple canonical meshes as truth. Use it for angle-response shape and calibrate to each asset's nominalRcsDbsm.",
            "why": "Simple synthetic meshes and the current whitebox facet-sum path can produce unrealistic absolute magnitudes.",
        },
    }
    write_json(ASSET_ROOT / "manifest.json", manifest)

    readme = """# Sinclair Radar RCS Asset Library

This folder contains project-generated canonical mesh assets for early RadarSim
RCS experiments.

These files are not measured RCS data and not production CAD. They are simple
OBJ meshes with JSON metadata so Sinclair can move from hard-coded RCS numbers
to a visible asset-backed RCS source.

Important:

- Do not treat raw `sim_rcs` absolute dBsm from these meshes as measured truth.
- Use `sim_rcs` for aspect-angle response shape first.
- Normalize or calibrate that shape to each asset's `nominalRcsDbsm` until a
  measured RCS table or validated CAD/material model is available.

Recommended source modes:

1. Scenario Assumption
   - fast preset RCS values
   - no mesh calculation

2. RadarSim Mesh RCS
   - use these OBJ files with `radarsimpy_whitebox.sim_rcs`
   - good for early angle sweep and Pd estimate workflows

3. Measured RCS Library
   - future validated table/distribution source

4. High-Fidelity Ray Trace / EM Solver
   - future openEMS/Meep/WiTwin-style backend

Coordinate convention:

- x: object forward/length axis
- y: object lateral/width axis
- z: height axis
- units: meters

Asset boundary:

- Project-generated, synthetic, canonical geometry.
- No external mesh license dependency.
- Not measured or ray-traced truth.
"""
    (ASSET_ROOT / "README.md").write_text(readme, encoding="utf-8")

    print(f"Generated {len(manifest_assets)} radar RCS assets in {ASSET_ROOT}")


if __name__ == "__main__":
    main()
